#!/usr/bin/env bash

set -euo pipefail

ROOT=/vepfs-mlp2/c20250301/240403026/async_vla
export GR00T_MODEL_PATH=${GR00T_MODEL_PATH:-"$ROOT/checkpoints/GR00T-N1.7-LIBERO/libero_spatial"}
export GR00T_BACKBONE_PATH=${GR00T_BACKBONE_PATH:-"$ROOT/.cache/huggingface/hub/models--nvidia--Cosmos-Reason2-2B/snapshots/9ce19a195e423419c349abfc86fd07178b230561"}

# Four-GPU clean profile: GPU 0 owns the frozen semantic server; GPUs 1-3 run rollout and PPO.
export ALLOWED_GPU_IDS=${ALLOWED_GPU_IDS:-0,1,2,3}
export SEMANTIC_GPU_IDS=${SEMANTIC_GPU_IDS:-0}
export DIT_GPU_IDS=${DIT_GPU_IDS:-1,2,3}
export ACTOR_GPU_IDS=${ACTOR_GPU_IDS:-1,2,3}
export TARGET_TRAIN_ENVS=${TARGET_TRAIN_ENVS:-240}
export TARGET_EVAL_ENVS=${TARGET_EVAL_ENVS:-120}
export ACTION_CHUNK_SIZE=${ACTION_CHUNK_SIZE:-16}
export TRAIN_ROLLOUT_STEPS=${TRAIN_ROLLOUT_STEPS:-256}
export EVAL_ROLLOUT_STEPS=${EVAL_ROLLOUT_STEPS:-${TRAIN_ROLLOUT_STEPS}}
export TRAIN_ROLLOUT_EPOCH=${TRAIN_ROLLOUT_EPOCH:-1}
export PPO_GLOBAL_BATCH_SIZE=${PPO_GLOBAL_BATCH_SIZE:-960}
export PPO_MICRO_BATCH_SIZE=${PPO_MICRO_BATCH_SIZE:-2}
export PPO_MAX_STEPS=${PPO_MAX_STEPS:-100}
export PPO_VAL_INTERVAL=${PPO_VAL_INTERVAL:-20}
export PPO_EVAL_BEFORE_TRAINING=${PPO_EVAL_BEFORE_TRAINING:-true}
export PPO_SAVE_INTERVAL=${PPO_SAVE_INTERVAL:--1}
export PPO_UPDATE_EPOCHS=${PPO_UPDATE_EPOCHS:-1}
export PPO_ACTOR_LR=${PPO_ACTOR_LR:-1.0e-7}
export PPO_VALUE_LR=${PPO_VALUE_LR:-2.0e-5}
export PPO_CRITIC_WARMUP_STEPS=${PPO_CRITIC_WARMUP_STEPS:-0}
export PPO_FILTER_REWARDS=false
export PPO_KL_BETA=0.0
export PPO_EXPERIMENT_NAME=${PPO_EXPERIMENT_NAME:-libero_spatial_ditonly_ppo_semantic_server_clean}
export SEMANTIC_PREPROCESS_PROXY=false
export SEMANTIC_MID_CHUNK_PUBLISH=true
export SEMANTIC_MID_CHUNK_FRAME=${SEMANTIC_MID_CHUNK_FRAME:-10}
export SEMANTIC_MID_CHUNK_MIN_FRAME=${SEMANTIC_MID_CHUNK_MIN_FRAME:-1}
export SEMANTIC_FETCH_TARGET_AGE_FRAMES=-1
export SEMANTIC_FETCH_HARD_MAX_AGE_FRAMES=-1
export SEMANTIC_EVAL_FIXED_AGE_FRAMES=-1
export INITIALIZE_PACKET_AGE_ADAPTER=true
export REQUIRE_PACKET_AGE_INPUT=true

exec bash "$ROOT/RLinf/examples/embodiment/run_gr00t_semantic_cache_sync_ppo.sh" libero_spatial_ditonly_ppo_semantic_server_clean
